2023-11-28 15:48:32 ERROR 400 response executing GraphQL.
2023-11-28 15:48:32 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2023-11-28 15:48:32 ERROR Traceback (most recent call last):
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1002, in sweep
    response = self.gql(
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/rlserver/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/cli/cli.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/cli/cli.py", line 1501, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/wandb_agent.py", line 583, in agent
    return run_agent(
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/wandb_agent.py", line 528, in run_agent
    agent.run()
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/wandb_agent.py", line 190, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/apis/internal.py", line 126, in sweep
    return self.api.sweep(*args, **kwargs)
  File "/home/rlserver/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: name required for project query (Error 400: Bad Request)

2023-11-28 15:54:25 INFO Running runs: []
2023-11-28 15:54:26 INFO Agent received command: run
2023-11-28 15:54:26 INFO Agent starting run with config:
	batch-size: 16
	epochs: 183
	fixed-size: [[512, 512], [256, 256], [128, 128], [64, 64]]
	lr: 0.009274385836419508
	lr-gamma: 0.4470706103036409
	lr-steps: [[50, 100], [100, 150]]
	weight-decay: 0.0001940215427525603
	with_FFCA: [True, False]
2023-11-28 15:54:26 INFO About to run command: /usr/bin/env python train.py --batch-size=16 --epochs=183 "--fixed-size=[[512, 512], [256, 256], [128, 128], [64, 64]]" --lr=0.009274385836419508 --lr-gamma=0.4470706103036409 "--lr-steps=[[50, 100], [100, 150]]" --weight-decay=0.0001940215427525603 "--with_FFCA=[True, False]"
2023-11-28 15:54:31 INFO Running runs: ['rjwy8ihx']
2023-11-28 15:54:31 INFO Cleaning up finished run: rjwy8ihx
2023-11-28 15:54:31 INFO Agent received command: run
2023-11-28 15:54:31 INFO Agent starting run with config:
	batch-size: 28
	epochs: 185
	fixed-size: [[512, 512], [256, 256], [128, 128], [64, 64]]
	lr: 0.006204977166051962
	lr-gamma: 0.35933502877470047
	lr-steps: [[50, 100], [100, 150]]
	weight-decay: 0.0003978745609906051
	with_FFCA: [True, False]
2023-11-28 15:54:31 INFO About to run command: /usr/bin/env python train.py --batch-size=28 --epochs=185 "--fixed-size=[[512, 512], [256, 256], [128, 128], [64, 64]]" --lr=0.006204977166051962 --lr-gamma=0.35933502877470047 "--lr-steps=[[50, 100], [100, 150]]" --weight-decay=0.0003978745609906051 "--with_FFCA=[True, False]"
2023-11-28 15:54:36 INFO Running runs: ['tlgq8a6h']
2023-11-28 15:54:36 INFO Cleaning up finished run: tlgq8a6h
2023-11-28 15:54:37 INFO Agent received command: run
2023-11-28 15:54:37 INFO Agent starting run with config:
	batch-size: 16
	epochs: 209
	fixed-size: [[512, 512], [256, 256], [128, 128], [64, 64]]
	lr: 0.0066677845222386815
	lr-gamma: 0.3586900280588148
	lr-steps: [[50, 100], [100, 150]]
	weight-decay: 0.0004621658178239344
	with_FFCA: [True, False]
2023-11-28 15:54:37 INFO About to run command: /usr/bin/env python train.py --batch-size=16 --epochs=209 "--fixed-size=[[512, 512], [256, 256], [128, 128], [64, 64]]" --lr=0.0066677845222386815 --lr-gamma=0.3586900280588148 "--lr-steps=[[50, 100], [100, 150]]" --weight-decay=0.0004621658178239344 "--with_FFCA=[True, False]"
2023-11-28 15:54:42 INFO Running runs: ['zv1qrba3']
2023-11-28 15:54:42 ERROR Detected 3 failed runs in the first 60 seconds, shutting down.
2023-11-28 15:54:42 INFO To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
